services:
  postgres:
    container_name: ujon-infra-pg
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=plcaeholder
      - POSTGRES_USER=plcaeholder
      - POSTGRES_PASSWORD=plcaeholder
      - TZ=UTC
    volumes:
      - plcaeholder:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

    

