services:
  postgres:
    container_name: ujon-infra-pg
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ujon_local
      - POSTGRES_USER=ujon
      - POSTGRES_PASSWORD=ujon_pw
      - TZ=UTC
    volumes:
      - .infra/postgres/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

    

