name: Validate database

on:
  push:
    paths:
      - "db/**"
    tags-ignore:
      - "*"
  pull_request:
    paths:
      - "db/**"
    tags-ignore:
      - "*"
  workflow_dispatch:

jobs:
  validate:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Decode Flyway config
        run: |
          echo "${{ secrets.FLYWAY_CONFIG }}" | base64 --decode > flyway.conf
          cat flyway.conf

      - name: Validate database
        uses: docker://redgate/flyway:10.21.0
        with:
          args: >-
            validate
            -configFiles=flyway.conf 
            -target=current