name: Migrate database

on:
  push:
    tags:
      - "migrate*"

jobs:
  migrate:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Decode Flyway config
        run: |
          echo "${{ secrets.FLYWAY_CONFIG }}" | base64 --decode > flyway.conf
          cat flyway.conf

      - name: Validate database
        uses: docker://redgate/flyway:10.21.0
        with:
          args: >-
            migrate
            -configFiles=flyway.conf